apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: test-py-16-azr 
  janus-idp.io/tekton: test-py-16-azr
  backstage.io/kubernetes-id: test-py-16-azr
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: test-py-16-azr
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml