apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: test-py-16-azr-gitops
  description: This is GitOps manifest for test-py-16-azr   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=test-py-16-azr
    backstage.io/kubernetes-id: test-py-16-azr 
    backstage.io/techdocs-ref: dir:.
    dev.azure.com/project-repo: prietyc123-qe-org/test-py-16-azr-gitops
    dev.azure.com/project: shared-public
    dev.azure.com/build-definition: prietyc123-qe-org.test-py-16-azr-gitops
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:test-py-16-azr
