apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: test-py-16-azr
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-py-16-azr 
  name: test-py-16-azr
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: test-py-16-azr 
